name: app_environment
channels:
  - snowflake
dependencies:
  - geopandas=0.14.2
  - matplotlib=3.9.2
  - python=3.11.*
  - snowflake-snowpark-python=1.28.0
  - streamlit=
  - streamlit-extras=0.4.0
  - pydeck=0.9.*