create or replace view DATAOPS_EVENT_PROD.HACKATHON_DATASETS.SOCIAL_VULNERABILITY_INDEX(
	GEO,
	OBJECTID COMMENT 'Unique identifier for each record in the table.',
	ST COMMENT 'Two-letter abbreviation for the type of social vulnerability index.',
	STATE COMMENT 'The abbreviated name of the U.S. state.',
	ST_ABBR COMMENT 'Two-letter abbreviations representing geographical locations or states.',
	STCNTY COMMENT 'Three-digit codes representing the statistical county or county equivalent for each record.',
	COUNTY COMMENT 'Names of counties.',
	FIPS COMMENT 'FIPS codes representing geographic locations.',
	LOCATION COMMENT 'Census tract or parish/county location descriptions.',
	AREA_SQMI COMMENT 'The size of the area in square miles.',
	E_TOTPOP COMMENT 'The total population estimate for the social vulnerability index.',
	M_TOTPOP COMMENT 'The total population measure in millions.',
	E_HU COMMENT 'A column holding data representing the European Union''s Harmonized System (HS) codes for trade classification of goods.',
	M_HU COMMENT 'A column holding data representing a social vulnerability index measurement.',
	E_HH COMMENT 'A column holding data representing an index for social vulnerability, specifically the East-West component.',
	M_HH COMMENT 'Measured values representing the number of hours in the Million Solar Transmission Project''s hourly energy production data.',
	E_POV150 COMMENT 'A column holding data representing the Social Vulnerability Index E_POV150.',
	M_POV150 COMMENT 'A column holding data representing the Social Vulnerability Index (M-POV150) measurement.',
	E_UNEMP COMMENT 'The column represents an employment-related vulnerability index.',
	M_UNEMP COMMENT 'The Monetary Value of Unemployment index.',
	E_HBURD COMMENT 'A column holding data representing the E-Business Risk Index score.',
	M_HBURD COMMENT 'A column holding data representing the median housing burden ratio.',
	E_NOHSDP COMMENT 'A column holding data representing the Social Vulnerability Index for Essential Emergency Services and Critical Public Health and Safety Infrastructure.',
	M_NOHSDP COMMENT 'A column holding data representing a measure of social vulnerability index without housing and economic data points.',
	E_UNINSUR COMMENT 'The number of uninsured social vulnerability units.',
	M_UNINSUR COMMENT 'The number of uninsured individuals or entities as measured by the social vulnerability index.',
	E_AGE65 COMMENT 'A column holding data indicating the number of records with an age of 65 or above.',
	M_AGE65 COMMENT 'Age indicator for individuals who are 65 years old or above.',
	E_AGE17 COMMENT 'A column holding data representing an age value, likely for individuals aged 17 or older.',
	M_AGE17 COMMENT 'Age values representing individuals who were 17 years old at the time of the event.',
	E_DISABL COMMENT 'A column holding data representing an electronic disability index.',
	M_DISABL COMMENT 'A column holding data representing a measure of disability index.',
	E_SNGPNT COMMENT 'A column holding data representing a social vulnerability index score.',
	M_SNGPNT COMMENT 'A column holding data representing a metric for calculating social vulnerability indices.',
	E_LIMENG COMMENT 'A column holding data representing an environmental vulnerability index score.',
	M_LIMENG COMMENT 'A column holding data representing a measure of medium-severity limit values.',
	E_MINRTY COMMENT 'A column holding data representing minimum risk scores.',
	M_MINRTY COMMENT 'A column holding data representing minimum risk scores.',
	E_MUNIT COMMENT 'A column holding data representing an electronic measurement unit.',
	M_MUNIT COMMENT 'Measured value in Monetary Units.',
	E_MOBILE COMMENT 'A column holding data representing the Social Vulnerability Index for mobile devices.',
	M_MOBILE COMMENT 'Mobile security vulnerability scores.',
	E_CROWD COMMENT 'A column holding data representing an electronic crowd sourced vulnerability score.',
	M_CROWD COMMENT 'A column holding data representing a social vulnerability index, \"M\\_CROWD\".',
	E_NOVEH COMMENT 'A column holding data representing an environmental noise index value.',
	M_NOVEH COMMENT 'A column holding data representing the number of motor vehicles involved in an incident.',
	E_GROUPQ COMMENT 'A column holding data representing an electronic groupquake severity index.',
	M_GROUPQ COMMENT 'A column holding data representing a measure of group vulnerability.',
	EP_POV150 COMMENT 'The first component of the Social Vulnerability Index, representing a numerical score.',
	MP_POV150 COMMENT 'The Social Vulnerability Index score, as measured by MP_POV150.',
	EP_UNEMP COMMENT 'The Social Vulnerability Index for unemployment rate.',
	MP_UNEMP COMMENT 'The Monmouth-Princeton Regional Unemployment Index.',
	EP_HBURD COMMENT 'The Social Vulnerability Index score indicating the potential for a location to experience negative effects due to a hazard event.',
	MP_HBURD COMMENT 'The metric representing the mean perceived hackability risk score.',
	EP_NOHSDP COMMENT 'The Social Vulnerability Index (SVI) score, a measure of the community''s susceptibility to natural or human-caused disasters.',
	MP_NOHSDP COMMENT 'The score representing the severity of social vulnerability, as measured by the NoHSDP method.',
	EP_UNINSUR COMMENT 'The column represents an index measuring the level of uninsured social vulnerability.',
	MP_UNINSUR COMMENT 'The index representing the percentage of uninsured population.',
	EP_AGE65 COMMENT 'The age of the system or infrastructure component, expressed as a floating-point number, indicating if it is considered old and potentially vulnerable at or above 65 years.',
	MP_AGE65 COMMENT 'The age of a system or application, measured in years, indicating its proximity to reaching 65 years old, a common threshold for retirement or end-of-life in IT infrastructure.',
	EP_AGE17 COMMENT 'The age of the social vulnerability index measurement, specifically for individuals aged 17.',
	MP_AGE17 COMMENT 'The age of a social vulnerability index measurement, applicable to individuals aged 17.',
	EP_DISABL COMMENT 'The score representing the exploitability and potential damage of a social vulnerability.',
	MP_DISABL COMMENT 'The severity score of a social vulnerability on a scale from 0 to 15.',
	EP_SNGPNT COMMENT 'The Social Vulnerability Index (SVI) sub-score for each feature, measured on a scale from 0 to 100.',
	MP_SNGPNT COMMENT 'The Social Vulnerability Index (MP\\_SNGPNT) measures the relative susceptibility of a location to social vulnerabilities.',
	EP_LIMENG COMMENT 'The Social Vulnerability Index with a limit value, measured on a continuous scale.',
	MP_LIMENG COMMENT 'The magnitude of the limit for a security vulnerability measurement.',
	EP_MINRTY COMMENT 'The minimum risk score for social vulnerability events.',
	MP_MINRTY COMMENT 'The minimum risk score for social vulnerability assessment.',
	EP_MUNIT COMMENT 'The numerical value representing the social vulnerability index per capita.',
	MP_MUNIT COMMENT 'The Monetary Unit for measuring the social vulnerability index.',
	EP_MOBILE COMMENT 'The Social Vulnerability Index score for mobile devices.',
	MP_MOBILE COMMENT 'The Mobile Platform Security Index score.',
	EP_CROWD COMMENT 'The Social Vulnerability Index score for crowd-sourced assessments.',
	MP_CROWD COMMENT 'The Social Vulnerability Index score for crowd-sourced data.',
	EP_NOVEH COMMENT 'The Social Vulnerability Index for novel ecosystems, measured on a floating point scale.',
	MP_NOVEH COMMENT 'The Social Vulnerability Index (MP\\_NOVEH) measures the relative potential for a place to experience social vulnerability.',
	EP_GROUPQ COMMENT 'The score representing the group''s vulnerability to social exploits on a continuous scale.',
	MP_GROUPQ COMMENT 'A column holding data representing a grouping score for machine learning model performance metrics.',
	EPL_POV150 COMMENT 'The Social Vulnerability Index score based on the EPL (Environmental Protection Agency) POV150 model.',
	EPL_UNEMP COMMENT 'The Social Vulnerability Index representing the percentage of the population that is unemployed.',
	EPL_HBURD COMMENT 'The score representing the estimated economic impact of a potential security vulnerability.',
	EPL_NOHSDP COMMENT 'The score representing the number of exploitable vulnerabilities per million lines of source code.',
	EPL_UNINSUR COMMENT 'The Social Vulnerability Index representing the proportion of uninsured population.',
	SPL_THEME1 COMMENT 'The score for Social Vulnerability Theme 1, representing the potential for exploitation of a social environment.',
	RPL_THEME1 COMMENT 'The score for the first theme in the social vulnerability index.',
	EPL_AGE65 COMMENT 'The age of a system or asset, in years, as determined by the Common Vulnerability Scoring System (CVSS) and used to calculate the Enterprise Security Risk Index (ESRI) score, specifically for assets with an impact on individuals aged 65 or older.',
	EPL_AGE17 COMMENT 'The age of a social vulnerability index measurement, calculated for populations aged 17 and above.',
	EPL_DISABL COMMENT 'The score representing the Enterprise Security Risk Index for disability events.',
	EPL_SNGPNT COMMENT 'The score representing the Social Vulnerability Index based on the Environmental Protection Agency''s Socio-economic Data and Mapping System (EN-DP).',
	EPL_LIMENG COMMENT 'The numerical value representing the enterprise security event limit for this index.',
	SPL_THEME2 COMMENT 'The score for the second theme in the Social Vulnerability Index.',
	RPL_THEME2 COMMENT 'The score representing the severity level of social vulnerability based on the RPL theme 2 index.',
	EPL_MINRTY COMMENT 'The minimum risk score in the Event Prioritization Model for social vulnerabilities.',
	SPL_THEME3 COMMENT 'The Social Vulnerability Index score for theme 3.',
	RPL_THEME3 COMMENT 'The score representing the risk level for a specific social vulnerability theme, as measured on a continuous scale.',
	EPL_MUNIT COMMENT 'The numerical value representing the Exploitability Score Multiplier Unit for each vulnerability record.',
	EPL_MOBILE COMMENT 'The score representing the mobile exposure posture of an entity based on the European Union''s European Cybersecurity Agency (EU-CSA) European Threat Landscape (ETL) model.',
	EPL_CROWD COMMENT 'The Social Vulnerability Index score for crowd-sourced data.',
	EPL_NOVEH COMMENT 'The score representing the European Union''s Environmental Performance Index for NOx emissions.',
	EPL_GROUPQ COMMENT 'The score representing an organization''s exposure to social vulnerabilities based on the Exploitability and Privilege Level (EPL) model.',
	SPL_THEME4 COMMENT 'A column holding data representing a social vulnerability index score, version 4.',
	RPL_THEME4 COMMENT 'The score representing the severity of social vulnerability based on the RPL theme 4 index.',
	SPL_THEMES COMMENT 'The Social Vulnerability Index, represented by this column, measures the potential for a given location to experience negative effects from a hazard event, including societal vulnerability.',
	RPL_THEMES COMMENT 'The Social Vulnerability Index with themes represented as continuous values.',
	F_POV150 COMMENT 'A column holding data representing a social vulnerability index, as measured by F_POV150.',
	F_UNEMP COMMENT 'The column represents a social vulnerability index component related to unemployment.',
	F_HBURD COMMENT 'A column holding data representing the Firefox browser security vulnerability index.',
	F_NOHSDP COMMENT 'A column holding data representing a social vulnerability index score.',
	F_UNINSUR COMMENT 'A column holding data representing the number of uninsured individuals or entities.',
	F_THEME1 COMMENT 'A column holding data representing a score for a specific theme in social vulnerability assessment.',
	F_AGE65 COMMENT 'A column holding data indicating if the record''s owner is 65 years old or older.',
	F_AGE17 COMMENT 'A column holding data representing an age value for a specific entity, potentially indicating eligibility for certain policies or services based on the age being 17.',
	F_DISABL COMMENT 'A column holding data representing a disability score.',
	F_SNGPNT COMMENT 'A column holding data representing a social vulnerability index score.',
	F_LIMENG COMMENT 'A column holding data representing a numerical value for a security vulnerability limit.',
	F_THEME2 COMMENT 'A column holding data representing a social vulnerability index theme with a decimal value.',
	F_MINRTY COMMENT 'A column holding data representing a minimum risk score.',
	F_THEME3 COMMENT 'A column holding data representing a social vulnerability index theme with a decimal value.',
	F_MUNIT COMMENT 'A column holding data representing a monetary unit.',
	F_MOBILE COMMENT 'A column holding data representing a mobile security vulnerability index.',
	F_CROWD COMMENT 'A column holding data representing a social vulnerability index score.',
	F_NOVEH COMMENT 'A column holding data representing a social vulnerability index, specifically the F\\_NOVEH score.',
	F_GROUPQ COMMENT 'A column holding data representing a social vulnerability group quota.',
	F_THEME4 COMMENT 'A column holding data representing a score or index value for a specific security theme.',
	F_TOTAL COMMENT 'A column holding data representing a total score for social vulnerability assessment.',
	E_DAYPOP COMMENT 'The estimated daily population affected by a social vulnerability event.',
	E_NOINT COMMENT 'A column holding data representing the integer part of a social vulnerability index score.',
	M_NOINT COMMENT 'A column holding data representing non-integer numerical values. (This description does not provide any insight into the meaning or interpretation of the values in the \"M\\_NOINT\" column.)',
	E_AFAM COMMENT 'A column holding data representing an electronic vulnerability assessment score.',
	M_AFAM COMMENT 'Measured value of the social vulnerability index for a specific area.',
	E_HISP COMMENT 'The column \"E_HISP\" holds numerical values representing an unspecified security or vulnerability index.',
	M_HISP COMMENT 'The MicroSoft Hacking Intelligence Score, a numerical representation of the severity of a Microsoft vulnerability.',
	E_ASIAN COMMENT 'A column holding data representing an index for social vulnerability related to East Asian populations.',
	M_ASIAN COMMENT 'A column holding data representing the Asian Metasploit Exploit Index score.',
	E_AIAN COMMENT 'A column holding data representing the Social Vulnerability Index for American Indian and Alaska Native populations.',
	M_AIAN COMMENT 'A column holding data representing the Social Vulnerability Index for American Indian and Alaska Native populations.',
	E_NHPI COMMENT 'The index representing the socioeconomic vulnerability of a population based on factors.',
	M_NHPI COMMENT 'The Microbial Risk Assessment (MRA) Normalized Housing Penalty Index (NHPI) value.',
	E_TWOMORE COMMENT 'A column holding data representing a social vulnerability index with a scale of two or more.',
	M_TWOMORE COMMENT 'A column holding data representing a measure or metric, likely a score, with a decimal value.',
	E_OTHERRACE COMMENT 'A column holding data representing other racial and ethnic categories.',
	M_OTHERRACE COMMENT 'A column holding data representing other race categories as per the Modified Offensive or Threatening Racial/Ethnic Slurs (M-OTHER) category in the Social Vulnerability Index.',
	EP_NOINT COMMENT 'The numerical score representing the severity of social vulnerability.',
	MP_NOINT COMMENT 'The numerical value representing the non-integer component of the social vulnerability index.',
	EP_AFAM COMMENT 'The Social Vulnerability Index (EP\\_AFAM) represents a continuous measure of the social vulnerability of a population.',
	MP_AFAM COMMENT 'The Social Vulnerability Index (SVI) sub-score for Access to Facilities and Services.',
	EP_HISP COMMENT 'The Social Vulnerability Index (EP\\_Hispanic) represents the Hispanic population''s social vulnerability score.',
	MP_HISP COMMENT 'The Social Vulnerability Index (MP-Hispanic) score, a measure of a community''s susceptibility to natural or human-caused disasters, based on demographic, economic, and infrastructure factors.',
	EP_ASIAN COMMENT 'The Social Vulnerability Index for Asian populations.',
	MP_ASIAN COMMENT 'The Social Vulnerability Index for Asian populations.',
	EP_AIAN COMMENT 'A column holding data representing the Social Vulnerability Index for American Indian and Alaska Native populations.',
	MP_AIAN COMMENT 'The Social Vulnerability Index (SVI) sub-score for American Indian and Alaska Native populations.',
	EP_NHPI COMMENT 'The Social Vulnerability Index (EP\\_NHPI) is a decimal value representing the relative vulnerability of a census tract to 15 social factors.',
	MP_NHPI COMMENT 'The Social Vulnerability Index (MP\\_NHPI) measures the relative vulnerability of a population to natural or human-induced disasters.',
	EP_TWOMORE COMMENT 'The Social Vulnerability Index with two additional related metrics.',
	MP_TWOMORE COMMENT 'A column holding data representing a social vulnerability index with two additional factors.',
	EP_OTHERRACE COMMENT 'A column holding data representing other race indices in the social vulnerability index.',
	MP_OTHERRACE COMMENT 'A column holding data representing the misconfiguration points in other race conditions.',
	SHAPE_LENGTH COMMENT 'The length of the geometric shape, measured in units of distance.',
	SHAPE_AREA COMMENT 'The area of the shape, measured in square units.'
) COMMENT='The table contains records of social vulnerability indices for various locations. Each record represents a specific location and includes demographic and socioeconomic data, such as population, housing, and poverty levels.'
 as

SELECT * FROM ORGDATACLOUD$INTERNAL$SUMMIT_HACKATHON.PUBLIC.SOCIAL_VULNERABILITY_INDEX;